// src/components/thread_list.tsx
import Taro, { Component } from '@tarojs/taro'
import { View } from '@tarojs/components'
import { Thread } from './thread'
import { Loading } from './loading'
import { IMember } from '../interfaces/member'
import { INode } from '../interfaces/node'

import './thread.css'

interface IProps {
  threads: IThread[],
  loading: boolean
}

interface IThread {
  title: string,
  member: IMember,
  node: INode,
  last_modified: number,
  id: number,
  replies: number
  key?: number
}

class ThreadList extends Component<IProps, {}> {
  static defaultProps = {
    threads: [],
    loading: true
  }

  render () {
    const { loading, threads } = this.props

    if (loading) {
      return <Loading />
    }

    const element = threads.map((thread) => {
      return (
        <Thread
          key={thread.id}
          node={thread.node}
          title={thread.title}
          last_modified={thread.last_modified}
          replies={thread.replies}
          tid={thread.id}
          member={thread.member}
        />
      )
    })

    return (
      <View className='thread-list'>
        {element}
      </View>
    )
  }
}

export { ThreadList }

// src/components/thread_list.vue
<template>
  <view className='thread-list'>
    <loading v-if="loading" />
    <thread
      v-else
      v-for="t in threads"
      :key="t.id"
      :node="t.node"
      :title="t.title"
      :last_modified="t.last_modified"
      :replies="t.replies"
      :tid="t.id"
      :member="t.member"
    />
  </view>
</template>

<script lang="ts">
import Vue from 'vue'
import Loading from './loading.vue'
import Thread from './thread.vue'
export default Vue.extend({
  components: {
    'loading': Loading,
    'thread': Thread
  },
  props: {
    threads: {
      type: Array,
      default: []
    },
    loading: {
      type: Boolean,
      default: true
    }
  }
})
</script>
