// src/pages/nodes/nodes.vue
<template>
  <view class='node-container'>
    <view v-for="item in allNodes" :key="item.title" class='container'>
      <view class='title'>
        <text style='margin-left: 5px'>{{item.title}}</text>
      </view>
      <view class='nodes'>
        <navigator
          v-for="node in item.nodes"
          :key="node.full_name"
          class='tag'
          :url="node | url"
        >
          <text>{{node.full_name}}</text>
        </navigator>
      </view>
    </view>
  </view>
</template>

<script lang="ts">
import Vue from 'vue'
import allNodes from './all_node'
import api from '../../utils/api'
import './nodes.css'

export default Vue.extend({
  data () {
    return {
      allNodes
    }
  },
  filters: {
    url (node) {
      return `/pages/node_detail/node_detail${api.queryString(node)}`
    }
  }
})
</script>

// src/pages/nodes/nodes.tsx
import Taro from '@tarojs/taro'
import React from 'react'
import { View, Text, Navigator } from '@tarojs/components'
import allNodes from './all_node'
import api from '../../utils/api'

import './nodes.css'

class Nodes extends React.Component<{}, {}> {
  config = {
    navigationBarTitleText: '节点'
  }

  render () {
    const element = allNodes.map(item => {
      const nodes = item.nodes.map(node => {
        return (
          <Navigator
            className='tag'
            url={`/pages/node_detail/node_detail${api.queryString(node)}`}
            key={node.full_name}
          >
            <Text>
              {node.full_name}
            </Text>
          </Navigator>
        )
      })
      return (
        <View key={item.title} className='container'>
          <View className='title'>
            <Text style='margin-left: 5px'>
              {item.title}
            </Text>
          </View>
          <View className='nodes'>
            {nodes}
          </View>
        </View>
      )
    })
    return (
      <View className='node-container'>
        {element}
      </View>
    )
  }
}

export default Nodes
